[2024-05-05T10:22:49.884+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T10:22:50.050+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_complex.get_entry_result manual__2024-05-05T10:22:28.612296+00:00 [queued]>
[2024-05-05T10:22:50.102+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_complex.get_entry_result manual__2024-05-05T10:22:28.612296+00:00 [queued]>
[2024-05-05T10:22:50.102+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T10:22:50.175+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): get_entry_result> on 2024-05-05 10:22:28.612296+00:00
[2024-05-05T10:22:50.224+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2043) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T10:22:50.232+0000] {standard_task_runner.py:63} INFO - Started process 2075 to run task
[2024-05-05T10:22:50.282+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_complex', 'get_entry_result', 'manual__2024-05-05T10:22:28.612296+00:00', '--job-id', '18', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_complex.py', '--cfg-path', '/tmp/tmp0d3ky1qc']
[2024-05-05T10:22:50.310+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask get_entry_result
[2024-05-05T10:22:50.507+0000] {task_command.py:426} INFO - Running <TaskInstance: example_complex.get_entry_result manual__2024-05-05T10:22:28.612296+00:00 [running]> on host b2b5d11d7cf5
[2024-05-05T10:22:50.830+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_complex' AIRFLOW_CTX_TASK_ID='get_entry_result' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T10:22:28.612296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T10:22:28.612296+00:00'
[2024-05-05T10:22:50.837+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T10:22:50.856+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-05T10:22:50.867+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo get_entry_result']
[2024-05-05T10:22:50.947+0000] {subprocess.py:86} INFO - Output:
[2024-05-05T10:22:50.950+0000] {subprocess.py:93} INFO - get_entry_result
[2024-05-05T10:22:50.954+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-05T10:22:50.955+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T10:22:51.017+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=get_entry_result, execution_date=20240505T102228, start_date=20240505T102250, end_date=20240505T102251
[2024-05-05T10:22:51.072+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T10:22:51.095+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T10:22:51.103+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
